server:
  port: 8090
spring:
  application:
    name: admin-api
eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:8761/eureka/

