spring:
  profiles:
    active: dev
log:
  active:
    profile: dev

---
#开发环境配置
spring:
  profiles: dev

server:
  port: 8801

eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:8761/eureka/

---
#生产环境
spring:
  profiles: prod

server:
  port: 8098
