spring:
  mvc:
      async:
        request-timeout: 20s
  profiles:
      include: common-dev
zuul:
  routes:
    admin-api:
      path: /admin-api/**
      serviceId: admin-api
    file-api:
      path: /file-api/**
      serviceId: file-server
    web-api:
      path: /web-api/**
      serviceId: web-api
  host:
    connection-request-timeout-millis: 20000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
ribbion:
  ReadTimeout: 20000
  SocketTimeout: 20000
