spring:
  datasource:
     driverClassName: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
     username: root
     password: 123456
     type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:/com/nzc/blog/business/mapper/*.xml
  type-aliases-package: com.nzc.blog.business.entity