server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  server:
    enableSelfPreservation: false
    peer-node-read-timeout-ms: 3000
    peer-node-connect-timeout-ms: 3000
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: myBlog_register
