server:
  port: 8671
spring:
  application:
    name:  myBlog_config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: ./config-repo
      discovery:
        enabled: true
        service-id: myBlog_config
      profile: dev
eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:8761/eureka/